apiVersion: v1
kind: Namespace
metadata:
  name: nirn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nirn-proxy
  namespace: nirn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nirn-proxy
  template:
    metadata:
      labels:
        app: nirn-proxy
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '9000'
    spec:
      containers:
        - name: nirn-proxy
          resources:
            requests:
              cpu: 4 # shared-cpu-4x
          image: ghcr.io/pluralkit/nirn-proxy:aaeda6383068f90d3b02b3eb5b0d8c28b11668b0
          env:
            - name: BIND_IP
              value: '0.0.0.0'
            - name: CLUSTER_DNS
              value: nirn-proxy-headless.nirn.svc
            - name: ALLOW_CONCURRENT_REQUESTS
              value: "true"
            - name: LOG_LEVEL
              value: trace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: nirn-proxy
  namespace: nirn
  annotations:
    service.fly.io/nirn-handlers: http
    service.fly.io/concurrency-kind: connections
    service.fly.io/concurrency-limit-soft: "50"
    service.fly.io/concurrency-limit-hard: "2000"
spec:
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - name: nirn
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nirn-proxy
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nirn-proxy-headless
  namespace: nirn
spec:
  clusterIP: None
  selector:
    app: nirn-proxy
  ports:
  - port: 8080
