app = "pluralkit-http-edge"
primary_region = "arn"
vm.size = "shared-cpu-4x"
deploy.strategy = "canary"
http_service.internal_port = 80
http_service.force_https = true
build.image = "alpine" # unused

experimental.machine_config = '''{
	"dns": {
		"nameservers": ["127.0.0.53"],
		"dns_forward_rules": [{
			"basename": "consul.",
			"addr": "127.0.0.1:53"
		}]
	},
	"containers": [
		{
			"name": "tailscale",
			"image": "tailscale/tailscale:latest",
			"env": {
				"PATH": "/bin:/usr/bin:/sbin:/usr/local/bin",
				"TS_HOSTNAME": "fly-http-edge",
				"TS_EXTRA_ARGS": "--accept-routes --advertise-tags tag:edge",
				"TS_USERSPACE": "false",
				"TS_ENABLE_HEALTH_CHECK": "true"
			},
			"healthchecks": [{
				"name": "tailscale_up",
				"timeout": 1,
				"http": {
					"method": "GET",
					"port": 9002,
					"path": "/healthz"
				}
			}],
			"secrets": [{ "env_var": "TS_AUTHKEY", "name": "TS_AUTHKEY" }]
		},
		{
			"name": "caddy",
			"image": "caddy:latest",
			"entrypoint": ["/usr/bin/caddy", "run", "-c", "/etc/caddy/Caddyfile"],
			"depends_on": [{ "name": "tailscale", "condition": "healthy" }]
		}
	]
}'''

[[files]]
	local_path = "fly/edge.Caddyfile"
	guest_path = "/etc/caddy/Caddyfile"
	processes = ["caddy"]

[[files]]
	local_path = "fly/edge.anycast.html"
	guest_path = "/etc/caddy/anycast.html"
	processes = ["caddy"]

[[files]]
	local_path = "fly/edge.stats.html"
	guest_path = "/etc/caddy/stats.html"
	processes = ["caddy"]

[[files]]
	local_path = "cdn-index.html"
	guest_path = "/etc/caddy/cdn.html"
	processes = ["caddy"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"
