apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example
spec:
  serviceName: example
  replicas: 6
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: test
        image: alpine:latest
        command: ["/bin/sleep", "inf"]
