apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gateway-sentry-url
spec:
  itemPath: vaults/acnop6sxzggtzwha2bulnpjj6i/items/answlkegt2uh4gf5i3ndes6eea
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pluralkit-gateway
spec:
  serviceName: pluralkit-gateway
  replicas: 57
  selector:
    matchLabels:
      app: pluralkit-gateway
  template:
    metadata:
      labels:
        app: pluralkit-gateway
      annotations:
        compute.fly.io/cpu-kind: performance
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '9000'
    spec:
      containers:
      - name: gateway
        image: ghcr.io/pluralkit/gateway:73103dc2b5bc4075d8edbaa14290b85fdd2a5828
        resources:
          requests:
            cpu: 1 # performance; 2G memory
        env:
        - name: RUST_LOG
          value: info
        - name: pluralkit__json_log
          value: "true"
        - name: pluralkit__run_metrics_server
          value: "true"
        - name: pluralkit__discord__client_id
          value: "466378653216014359"
        - name: pluralkit__discord__cluster__total_shards
          value: "912"
        - name: pluralkit__discord__cluster__total_nodes
          value: "57"
        - name: pluralkit__discord__max_concurrency
          value: "16"
        - name: pluralkit__runtime_config_key
          value: 'gateway-k8s'
          # gets turned into node_id by rust code
        - name: STATEFULSET_NAME_FOR_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: pluralkit__discord__client_secret
          value: "1"
        - name: pluralkit__discord__api_base_url
          value: "pluralkit-nirn-proxy.flycast"
        - name: pluralkit__sentry_url
          valueFrom:
            secretKeyRef:
              name: gateway-sentry-url
              key: credential
        - name: pluralkit__db__data_db_uri
          value: "postgresql://pluralkit@[fdaa:9:e856:a7b:35c:0:a:102]:5432/pluralkit"
        - name: pluralkit__db__db_password
          valueFrom:
            secretKeyRef:
              name: database-password
              key: credential
        - name: pluralkit__discord__bot_token
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: credential
        - name: pluralkit__db__data_redis_addr
          value: "redis://[fdaa:9:e856:a7b:35c:0:a:102]:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: pluralkit-gateway
spec:
  clusterIP: None
  selector:
    app: pluralkit-gateway
  ports:
  - port: 5000
