# for some reason updating the configmap does not update the deployment
# so you need to run `kubectl -nkube-system rollout restart deployment/vmagent`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
    spec:
      serviceAccountName: vmagent
      containers:
      - name: vmagent
        image: victoriametrics/vmagent:latest
        args:
          - "-remoteWrite.url=http://vm.svc.pluralkit.net/insert/0/prometheus/api/v1/write"
          - "-enableTCP6"
          - "-promscrape.config=/etc/vmagent/vmagent.yml"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/vmagent
      volumes:
        - name: config-volume
          configMap:
            name: vmagent
            items:
              - key: vmagent.yml
                path: vmagent.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent
  namespace: kube-system
data:
  vmagent.yml: |
    global:
      scrape_interval: "15s"
    scrape_configs:
      - job_name: kubernetes
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__]
          action: replace
          regex: (.*)
          replacement: $1:9000
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent
  namespace: kube-system
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmagent
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmagent
subjects:
- kind: ServiceAccount
  name: vmagent
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmagent
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: vmagent-sa-secret
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: vmagent
type: kubernetes.io/service-account-token
