app = "pluralkit-grafana"
primary_region = "sjc"
build.dockerfile = "Dockerfile.grafana"
http_service.internal_port = 3000

[env]
	GF_INSTALL_PLUGINS = "https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/v0.10.3/victoriametrics-datasource-v0.10.3.zip;victoriametrics-datasource,grafana-opensearch-datasource"
	GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS = "victoriametrics-datasource"


[[files]]
	guest_path = "/etc/grafana/provisioning/datasources/victoriametrics.yml"
	local_path = "grafana-provision-datasource-victoriametrics.yml"

[[files]]
	guest_path = "/etc/grafana/provisioning/datasources/opensearch.yml"
	local_path = "grafana-provision-datasource-opensearch.yml"
