app = "pluralkit-victoriametrics"
primary_region = "sjc"
vm.cpus = 2
vm.memory = "4GB"
build.dockerfile = "Dockerfile.victoriametrics"

[processes]
	vminsert = "/usr/local/bin/vminsert-prod -enableTCP6 -storageNode=d891261c63d2d8.vm.pluralkit-victoriametrics.internal -storageNode=e82d392c74e748.vm.pluralkit-victoriametrics.internal -storageNode=e78437e2f39e58.vm.pluralkit-victoriametrics.internal"
	vmselect = "/usr/local/bin/vmselect-prod -enableTCP6 -storageNode=d891261c63d2d8.vm.pluralkit-victoriametrics.internal -storageNode=e82d392c74e748.vm.pluralkit-victoriametrics.internal -storageNode=e78437e2f39e58.vm.pluralkit-victoriametrics.internal -vmalert.proxyURL=http://pluralkit-vmalert.internal:8880"
	vmstorage = "/usr/local/bin/vmstorage-prod -enableTCP6 -retentionPeriod=30d -storageDataPath=/data"
	vmauth = "/usr/local/bin/vmauth-prod -enableTCP6 -auth.config=/vmauth.yml"

# scrape metrics ?

[http_service]
	internal_port = 8427
	processes = ["vmauth"]

[[files]]
	guest_path = "/vmauth.yml"
	local_path = "vmauth.yml"
	processes = ["vmauth"]

[[mounts]]
	source = "vminsert_placement"
	destination = "/unused"
	processes = ["vminsert"]
	initial_size = "1gb"

[[mounts]]
	source = "vmselect_placement"
	destination = "/unused"
	processes = ["vmselect"]
	initial_size = "1gb"

[[mounts]]
	source = "vmauth_placement"
	destination = "/unused"
	processes = ["vmauth"]
	initial_size = "1gb"

[[mounts]]
	source = "vmstorage"
	destination = "/data"
	processes = ["vmstorage"]
	initial_size = "10gb"
