app = "pluralkit-opensearch"
primary_region = "sjc"
build.dockerfile = "Dockerfile.opensearch"

[env]
	"discovery.seed_hosts" = "pluralkit-opensearch.internal"
	"network.publish_host" = "fly-local-6pn"
	"bootstrap.memory_lock" = "true"
	"plugins.security.disabled" = "true"
	DISABLE_INSTALL_DEMO_CONFIG = "true"

[http_service]
	internal_port = 9200

	[http_service.concurrency]
		type = "requests"
		soft_limit = 250
		hard_limit = 250

[mounts]
	source = "opensearch_data"
	destination = "/usr/share/opensearch/data"
	initial_size = "100gb"

[[vm]]
	size = "performance-2x"
	memory = "8gb"
