route:
  group_by: ['alertgroup']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: discord
receivers:
  - name: discord
    discord_configs:
      - webhook_url_file: '/etc/pluralkit/alertmanager-webhook'
