groups:
  - name: gateway
    interval: 1m
    rules:
      - alert: gateway_latency
        expr: 'avg(pluralkit_gateway_shard_latency) > 200'
        for: 5m
        labels:
          alertgroup: 'gateway'
        annotations:
          name: 'High Gateway Latency'
          summary: 'Average shard latency is above 200ms'
          dashboard: 'https://grafana.pluralkit.me/explore?orgId=1'
      - alert: gateway_events
        expr: 'rate(pluralkit_gateway_events_shard[15m]) == 0'
        labels:
          alertgroup: 'gateway'
        annotations:
          name: 'No Events Recieved'
          summary: 'Shard {{ $labels.shard_id }} has recieved 0 events over the past 15m'
          dashboard: 'https://grafana.pluralkit.me/explore?orgId=1'
  - name: backups
    interval: 1h
    rules:
      - alert: backup_age
        expr: 'pluralkit_latest_backup_age > (7 * 24 * 60 * 60)' #7 days
        labels:
          alertgroup: 'backups'
        annotations:
          name: 'High Backup Age'
          summary: 'Last backup for `{{ $labels.repo }}` is older than 1 week'
          dashboard: 'https://grafana.pluralkit.me/explore?orgId=1'