groups:
  - name: general
    interval: 10s
    rules:
      - alert: out_of_memory
        expr: '_msg: "Out of memory" | stats count() as errorLog | filter errorLog:>0'
        labels:
          alertgroup: 'general'
        annotations:
          name: 'Out of memory'
          dashboard: 'http://grafana.pluralkit.me/explore?orgId=1'
