{
 "title": "PluralKit API",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Reqs/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pk_http_requests_count{domain=\"api.pluralkit.me\"}[$__rate_interval])) by (domain)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(pk_http_requests_bucket{domain=\"api.pluralkit.me\"}[5m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pk_http_requests_bucket{domain=\"api.pluralkit.me\"}[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pk_http_requests_bucket{domain=\"api.pluralkit.me\"}[5m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(pk_http_requests_count{domain=\"api.pluralkit.me\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Reqs by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (route) (rate(pk_http_requests_count{domain=\"api.pluralkit.me\"}[$__rate_interval]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "p99 atency by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(pk_http_requests_bucket{domain=\"api.pluralkit.me\"}[5m])) by (le, route))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  }
 ]
}