{
 "title": "PluralKit",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "systems",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value\nFROM systems\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value\nFROM members\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "groups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value\nFROM groups\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "guilds (last 1 week)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value\nFROM guilds\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "switches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value\nFROM switches\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value\nFROM messages\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value\nFROM guilds\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "options": { "content": "​\n# guilds" },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value\nFROM channels\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 8 },
   "options": { "content": "​\n# channels" },
   "targets": [
    {}
   ]
  },
  {
   "title": "systems & members",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value as systems\nFROM systems\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value as members\nFROM members\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  }
 ]
}