app = "pluralkit-sjc-k8s"
primary_region = "sjc"
vm.size = "performance-1x"

[[services]]
protocol = "tcp"
internal_port = 6443
ports = [{ port = 6443 }]

[[services.checks]]
port = 9090
type = "http"
interval = "10s"
timeout = "2s"
grace_period = "5s"
method = "get"
path = "/livez"
protocol = "http"

[[services.checks]]
port = 9090
type = "http"
interval = "10s"
timeout = "2s"
grace_period = "5s"
method = "get"
path = "/readyz"
protocol = "http"
