version: "3"


services:
  scheduled_tasks:
    image: ghcr.io/pluralkit/pluralkit:62c5c3865a77cc3becd3c1e8e36e91637741e15d
    command: ["bin/PluralKit.ScheduledTasks.dll"]
    environment:
      - "PluralKit:Database=Host=10.0.1.3;Port=5432;Username=pluralkit;Password=${DATABASE_PASSWORD};Database=pluralkit;Maximum Pool Size=10;Minimum Pool Size=10;Max Auto Prepare=10"
      - "PluralKit:InfluxUrl=http://10.0.1.3:8086"
      - "PluralKit:InfluxDb=pluralkit"
      - "PluralKit:UseRedisMetrics=true"
      - "PluralKit:RedisAddr=10.0.1.3:6379"
      - "PluralKit:ConsoleLogLevel=2"
      - "PluralKit:FileLogLevel=5"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - 10.0.1.2:3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-data:/var/lib/grafana
    restart: unless-stopped