name: Docker build

on:
  push:
    branches: [ main ]
    paths:
      - 'backups/'

jobs:
  image:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: backups/
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/pluralkit/backups:${{ github.sha }}
            ghcr.io/pluralkit/backups:latest
          labels: ${{ steps.meta.outputs.labels }}
